left_toe_indices: [
  5773, 5781, 5782, 5791, 5793, 5805, 5808, 5816, 5817, 5830, 5831,
  5859, 5860, 5906, 5907, 5908, 5909, 5912, 5914, 5915, 5916, 5917]
left_heel_indices: [
  8888, 8889, 8891, 8909, 8910, 8911, 8913, 8914, 8915, 8916, 8917,
  8918, 8919, 8920, 8921, 8922, 8923, 8924, 8925, 8929, 8930, 8934]
right_toe_indices: [
  8467, 8475, 8476, 8485, 8487, 8499, 8502, 8510, 8511, 8524, 8525,
  8553, 8554, 8600, 8601, 8602, 8603, 8606, 8608, 8609, 8610, 8611]
right_heel_indices: [
  8676, 8677, 8679, 8697, 8698, 8699, 8701, 8702, 8703, 8704, 8705,
  8706, 8707, 8708, 8709, 8710, 8711, 8712, 8713, 8714, 8715, 8716]

keypoints:
  - { name: 'pelvis',                 body: 'pelvis',        }
  - { name: 'left_hip_keypoint',      body: 'left_hip',      }
  - { name: 'left_knee_keypoint',     body: 'left_knee',     }
  - { name: 'left_ankle_keypoint',    body: 'left_ankle',    }
  - { name: 'left_heel_keypoint',     body: '',              }
  - { name: 'left_toe_keypoint',      body: '',              }
  - { name: 'right_hip_keypoint',     body: 'right_hip',     }
  - { name: 'right_knee_keypoint',    body: 'right_knee',    }
  - { name: 'right_ankle_keypoint',   body: 'right_ankle',   }
  - { name: 'right_heel_keypoint',    body: '',              }
  - { name: 'right_toe_keypoint',     body: '',              }
  - { name: 'torso_keypoint',         body: 'pelvis',        }
  - { name: 'left_shoulder_keypoint', body: 'left_shoulder', }
  - { name: 'left_elbow_keypoint',    body: 'left_elbow',    }
  - { name: 'left_wrist_keypoint',    body: 'left_wrist',    }
  - { name: 'right_shoulder_keypoint',body: 'right_shoulder',}
  - { name: 'right_elbow_keypoint',   body: 'right_elbow',   }
  - { name: 'right_wrist_keypoint',   body: 'right_wrist',   }